#!/bin/sh

# Brew
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib

# GPG
export GPG_TTY=$(tty)

if [ -e $HOME/.zshrc ]; then
    . $HOME/.zsh_extras
fi

if [ -e $HOME/.bashrc ]; then
    . $HOME/.bashrc
fi

if [ -e $HOME/.dotfiles/node/nvm ]; then
    . $HOME/.dotfiles/node/nvm
fi

if [ -e $HOME/.dotfiles/python/python ]; then
    command -v python3 >/dev/null 2>&1 && source $HOME/.dotfiles/python/python
    command -v python >/dev/null 2>&1 && source $HOME/.dotfiles/python/python
fi

brew list android-studio &>/dev/null
if [ $? -eq 0 ]; then
    export ANDROID_HOME=$HOME/Library/Android/sdk
    export PATH=$ANDROID_HOME/platform-tools:$PATH
    export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jbr/Contents/Home
fi

export VISUAL=vim
export EDITOR="$VISUAL"

cd_list_dir () {
    cd $1
    ls
}

alias ls='ls -FG'
alias ll='ls -ahl'
alias gh='history | grep'
alias current_branch='git rev-parse --abbrev-ref HEAD'
alias cdl='cd_list_dir'
