#!/bin/sh

alias ls='ls -FG'
alias ll='ls -ahl'

alias gh='history | grep'

alias cpv='rsync -ah --info=progress2'

case $SHELL in

  '/bin/zsh')
    if [ -e $HOME/.dotfiles/shell/zsh_aliases ]; then
      source $HOME/.dotfiles/shell/zsh_aliases
    fi
    ;;

  '/bin/bash')
    if [ -e $HOME/.dotfiles/shell/bash_aliases ]; then
      source $HOME/.dotfiles/shell/bash_aliases
    fi
    ;;
  *)
    echo "Unrecognised Shell"
    echo "Only supports ZSH and Bash at the moment"
    ;;
esac
