#!/bin/bash

command_result='\[\e[0;$(($?==0?32:31))m\]$\[\e[m\]'
open_bracket='\[\e[0;$(($?==0?32:31))m\][\[\e[m\]'
close_bracket='\[\e[0;$(($?==0?32:31))m\]]\[\e[m\]'
user='\[\e[0;36m\]\u\[\e[m\]'
host='\[\e[0;35m\]\h\[\e[m\]'
path='\[\e[38;5;214m\]\w\[\e[m\]'
suffix='\[\e[0;34m\]\=>\[\e[m\]'
export PS1="${open_bracket}${user}@${host}:${path}${close_bracket}\n${command_result} "
