#!/bin/bash

alias ls='ls -FG'
alias ll='ls -ahl'

alias gh='history | grep'

alias cpv='rsync -ah --info=progress2'

export PS1="[\e[1;36m\u\e[0m@\e[1;31m\h \e[0m \e[1;35m\w\e[0m ]\$ "
export PS2='=> '

if [ -e $HOME/.dotfiles/node/nvm ]; then
    command -v nvm >/dev/null 2>&1 && source $HOME/.dotfiles/node/nvm
fi

if [ -e $HOME/.dotfiles/python/python ]; then
    command -v python3 > /dev/null 2>&1 && { source $HOME/.dotfiles/python/python }
    command -v python > /dev/null 2>&1 && source $HOME/.dotfiles/python/python
fi