#!/bin/zsh

autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' [%b]'
autoload -U colors && colors

setopt PROMPT_SUBST
export PS1='%(?.%F⚡️ %f.%F🌧  %f)%F{cyan}%n%f => %F{red}%m:%f%F{magenta}${PWD/#$HOME/~}%f%F{green}${vcs_info_msg_0_}%f %F{yellow}\$%f '
export PS2='=> '
