#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if ! [ -x "$(command -v brew)" ]; then
    echo "Requires Brew to be installed"
    if [ "$1" == "setup" ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        exit 1
    fi
fi

if [ "$1" == "sync" ]; then
    cd brew
    brew bundle dump --force
else
    brew update
    brew upgrade
    brew bundle --file brew/Brewfile
fi
