#!/usr/bin/env bash

install_package() {
    if [[ "$PLATFORM" == "mac" ]]; then
        brew install "$@"
    elif [[ "$PLATFORM" == "linux" || "$PLATFORM" == "wsl" ]]; then
        sudo apt-get install -y "$@"
    elif [[ "$PLATFORM" == "windows" ]]; then
        choco install -y "$@"
    fi
}


# Detect platform
if grep -qi microsoft /proc/version; then
    PLATFORM="wsl"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="mac"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="linux"
else
    PLATFORM="windows"
fi
echo "Detected platform: $PLATFORM"

export PLATFORM