#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if ! [ -x "$(command -v git)" ]; then
    echo "Requires Git to be installed"
    echo "How did you get to this point?!"
    exit 1
fi

if [ "$1" == "setup" ]; then
    if [ -s ~/.gitconfig ]; then
        mv ~/.gitconfig archive/ 2>/dev/null
    fi
    if [ -L ~/.gitconfig ]; then
        rm ~/.gitconfig
    fi
    ln -s $HOME/.dotfiles/git/gitconfig ~/.gitconfig

    if [ -s ~/personal/.gitconfig-personal ]; then
        mv ~/personal/.gitconfig-personal archive/ 2>/dev/null
    fi
    if [ -L ~/personal/.gitconfig-personal ]; then
        rm ~/personal/.gitconfig-personal
    fi
    ln -s $HOME/.dotfiles/git/gitconfig-extended ~/personal/.gitconfig-personal
fi

if [ "$1" == "work" ]; then
    mkdir -p ~/work/
    if [ -s ~/work/.gitconfig-work ]; then
        mv ~/work/.gitconfig-work archive/ 2>/dev/null
    fi
    cp git/gitconfig-extended ~/work/.gitconfig-work
fi
