#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
    echo "Error: script only runs on none Mac Unix machines"
    exit 1
fi

if ! [ -x "$(command -v sudo)" ]; then
    apt-get install nodejs npm -y
else
    sudo apt-get install nodejs npm -y
fi

if ! [ -s ~/.nvm ]; then
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
fi
