#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
    echo "Error: script only runs on none Mac Unix machines"
    exit 1
fi

echo "Dock setup"
defaults read com.apple.dock >~/.dotfiles/archive/mac_os_dock

defaults write com.apple.dock orientation left
defaults write com.apple.dock mineffect -string scale
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock tilesize -int 40
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -int 48
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -int 0
killall Dock

echo "Finder setup"
defaults read com.apple.finder >~/.dotfiles/archive/mac_os_finder

defaults write com.apple.finder ShowRecentTags -bool false
defaults write com.apple.finder NewWindowTargetPath file:///Users/$(whoami)/
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowSidebar -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
killall finder

echo "Screenshots setup"
defaults read com.apple.screencapture >~/.dotfiles/archive/mac_os_screencapture

defaults write com.apple.screencapture type jpg
mkdir ~/Pictures/screenshots
defaults write com.apple.screencapture location ~/Pictures/screenshots

echo "Autocorrect setup"
defaults read NSGlobalDomain >~/.dotfiles/archive/mac_os_autocorrect

defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

echo "Terminal setup"
defaults read com.apple.terminal >~/.dotfiles/archive/mac_os_terminal

defaults write com.apple.terminal "Startup Window Settings" "Pro"
defaults write com.apple.terminal "Default Window Settings" "Pro"

echo "Keyboard and Mouse setup"
defaults read -g com.apple.swipescrolldirection >~/.dotfiles/archive/mac_os_swipescrolldirection
defaults read -g KeyRepeat >~/.dotfiles/archive/mac_os_keyboard
defaults read -g InitialKeyRepeat >>~/.dotfiles/archive/mac_os_keyboard

defaults write -g com.apple.swipescrolldirection -int 0
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15
