#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
    echo "Error: script only runs on none Mac Unix machines"
    exit 1
fi

if ! [ -x "$(command -v sudo)" ]; then
    apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev -y
else
    sudo apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev -y
fi

curl https://pyenv.run | bash
