#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/.."

source scripts/common
mkdir -p ~/personal/

if [ "$PLATFORM" = "mac" ]; then
    echo "### Brew ###"
    scripts/brew
fi

echo "### Shell ###"
scripts/shell update
scripts/shell setup

echo "### Git ###"
scripts/git setup

ACTION="${1:-}"
if [ "$ACTION" = "work" ]; then
    mkdir -p ~/work/
    custom_aliases=".custom_aliases"
    if [ -s ~/$custom_aliases ]; then
        touch ~/.custom_aliases
    fi
    echo "### Work Git ###"
    scripts/git work
fi

echo "### Vim ###"
scripts/vim setup

echo "### VScode ###"
scripts/vscode setup

echo "### Pyenv ###"
scripts/pyenv
echo "### NPM ###"
scripts/npm

echo "### GPG ###"
scripts/gpg
echo "### SSH ###"
scripts/ssh

if ! [ -L ~/personal/dotfiles ]; then
    ln -s ~/.dotfiles ~/personal/dotfiles
fi

exec $SHELL
