#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ "$1" == "setup" ]; then
    if [ -s ~/.zprofile ]; then
        mv ~/.zprofile ~/.dotfiles/archive/ 2>/dev/null
    fi
    if [ -s ~/.bash_profile ]; then
        mv ~/.bash_profile ~/.dotfiles/archive/ 2>/dev/null
    fi
    if [ -s ~/.zsh_prompt ]; then
        mv ~/.zsh_prompt ~/.dotfiles/archive/ 2>/dev/null
    fi
    if [ -s ~/.bash_prompt ]; then
        mv ~/.bash_prompt ~/.dotfiles/archive/ 2>/dev/null
    fi
    source_command="source ~/.dotfiles/shell/profile"
    case $SHELL in
    *'zsh'*)
        if [ -x "$(grep -Fxq "$source_command" ~/.zshrc)" ]; then
            echo $source_command >>~/.zshrc
        fi
        ;;
    *'bash'*)
        if [ -x "$(grep -Fxq "$source_command" ~/.bashrc)" ]; then
            echo $source_command >>~/.bashrc
        fi
        ;;
    esac
fi

if [ "$1" == "update" ]; then
    if ! [ "$(uname -s)" = "Darwin" ]; then
        if [ -x "$(command -v apt-get)" ]; then
            if [ -x "$(command -v sudo)" ]; then
                sudo apt-get update -y
                exit 0
            else
                apt-get update -y
                exit 0
            fi
        fi
        if [ -x "$(command -v yum)" ]; then
            if [ -x "$(command -v sudo)" ]; then
                sudo yum update -y
                exit 0
            else
                yum update -y
                exit 0
            fi
        fi
    fi
fi
