#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if ! [ -x "$(command -v vim)" ]; then
    echo "Requires Vim to be installed";
    exit 1;
fi

if [ "$1" == "setup" ]; then
    if [ -s ~/.vimrc ]; then
        mv ~/.vimrc archive/ &>/dev/null
    fi
    ln -s vim/vimrc ~/.vimrc
fi
