#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if ! [ -x "$(command -v code)" ]; then
    echo "Requires VScode to be installed"
    exit 1
fi

if [ "$1" == "setup" ]; then
    if [ "$(uname -s)" = "Darwin" ]; then
        if [ -s ~/Library/Application\ Support/Code/User/settings.json ]; then
            mv ~/Library/Application\ Support/Code/User/settings.json /archive/ 2>/dev/null
        fi
        ln -s vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
    else
        echo "Need to manually create the symlink for the settings file on non Mac systems"
        echo "If using WSL then the settings will live somewhere near here"
        echo "/mnt/c/Users/USERNAME/AppData/Roaming/Code/User/settings.json"
        echo "You'll have to copy the file into place" # Until I find a way to link them properly
        # Unsure on the default unix locations
    fi
fi

if [ "$1" == "sync" ]; then
    code --list-extensions | xargs -L 1 echo code --install-extension >vscode/extensions
else
    . vscode/extensions
fi
